server:
  port: 8080
  servlet:
    context-path: /app
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.200.64:5432/my_shop?currentSchema=jpa
    username: postgres
    password: 19771050
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

